export const NIGHT_LIGHTES = [
    'night-color-1',  'night-color-2',  'night-color-3',
    'night-color-4',  'night-color-5',  'night-color-6',
    'night-color-7',  'night-color-8',  'night-color-9',
    'night-color-10', 'night-color-11', 'night-color-12',
    'night-color-13', 'night-color-14', 'night-color-15',
    'night-color-16', 'night-color-17', 'night-color-18',
    'night-color-19', 'night-color-20', 'night-color-21',
    'night-color-22', 'night-color-23', 'night-color-24',
    'night-color-25', 'night-color-26', 'night-color-27',
    'night-color-28', 'night-color-29', 'night-color-30',
    'night-color-31', 'night-color-32', 'night-color-33',
    'night-color-34', 'night-color-35', 'night-color-36',
    'night-color-37', 'night-color-38', 'night-color-39',
    'night-color-40', 'night-color-41', 'night-color-42',
    'night-color-43', 'night-color-44', 'night-color-45',
    'night-color-46', 'night-color-47', 'night-color-48',
    'night-color-49', 'night-color-50', 'night-color-51',
    'night-color-52', 'night-color-53', 'night-color-54',
    'night-color-55', 'night-color-56', 'night-color-57',
    'night-color-58', 'night-color-59', 'night-color-60'
  ];